Vagrant.require_version '>= 1.8.0'

Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant"

    config.vm.define "mybox" do |mybox|
        mybox.vm.box = "ubuntu/trusty64"
        mybox.vm.hostname = "mybox.home"
        mybox.vm.network "forwarded_port", guest: 22, host: 10100
        mybox.vm.network "private_network", ip: "10.100.198.200"
        mybox.vm.provider "virtualbox" do |v|
            v.memory = 2048
        end
    end
end
